### ISSUE TITLE
Mehrzeilige Commands nicht mehr Funktionsfähig und Editierbar

### ISSUE THREAD

**Issue by Ushantilp** [Kirschn/KirschnBot#10]
Gerade beim Testen ist mit Aufgefallen das Mehrzeilige Commands die Man über das Webinterface Erstellt nicht mehr Klappen, was vorher Problem los ging.
Sprich wenn ich einen Command erstelle wie mein !listcom Command konnte ich vorher einfach in die Texteingabe eingeben

"Folgende Commands können benutzt werden:
Für Alle: ( Liste der Commands für Alle ) 
Mods Only: ( Liste der Commands für Mods )"

und der Bot hat dann Ausgegeben
KirschnBot: Folgende Commands können benutzt werden:
KirschnBot: Für Alle: ( Liste der Commands für Alle )
KirschnBot: Mods Only: ( Liste der Commands für Mods )

Jetzt gibt der Bot nurnoch die erste Zeile aus...

Das fand ich eigentlich sehr Angenehm weil so dann auch ein wenig mehr Übersicht vorhanden war..

Des weiteren Lassen sich solche Mehrzeiligen Commands auch nicht mehr übers Webinterface Editieren, alle anderen hingegen schon

**Comment by malarisch** [comment]
Das ist beabsichtigt, der Bot fällt sonst zu schnell ins Twitch Limit
