### ISSUE TITLE
(GER) Hilfe Seite im Webinterface

### ISSUE THREAD

**Issue by Ushantilp** [Kirschn/KirschnBot#6]
Da nicht jeder immer den umweg über Github gehen will zum nachschauen, wäre vielleicht ein "Hilfe" Tab wo halt die Parameter die man benutzen kann stehen, mit ner Kurzen erklärung damit man auch mal schnell eben Nachschauen kann

**Comment by malarisch** [comment]
Ist sowieso schon in Planung, konnte mich bis jetzt nur noch nicht durchdringen sowas im "großen Stil" anzulegen :D

**Comment by Ushantilp** [comment]
Ah okey wenn du willst kann ich da auch nen Dokument neben bei Fertig machen das kann man dann ja einpflegen muss natürlich dann nur von Fehlern bereinigt werden
